global:
  scrape_interval: 1m  # Default is fine
  evaluation_interval: 1m  # Default is fine

scrape_configs:
  - job_name: 'python-metrics'
    static_configs:
      - targets: ['metrics-app:8000']
